import csv
import time
from pathlib import Path
import json
from collections import defaultdict

import pandas as pd
import opendssdirect as dss
from kafka import KafkaConsumer

from .kafka_config import BOOTSTRAP_SERVERS, TOPIC
from simulation.opendss_utils import (
    compile_feeder,
    get_load_telemetry,
    get_circuit_topology,
    get_solution_metrics,
)

BASE_DIR = Path(__file__).resolve().parent.parent

DIGITAL_TWIN_OUTPUT = (
    BASE_DIR /
    "simulation" /
    "digital_twin_telemetry.csv"
)

# --------------------------------------------------
# Phase-0 validation log (RES.md D10 Phase 0)
# --------------------------------------------------

VALIDATION_LOG = (
    BASE_DIR /
    "simulation" /
    "phase0_validation_log.csv"
)

VALIDATION_FIELDS = [
    "timestamp",
    "datetime",
    "converged",
    "iterations",
    "v_pu_min",
    "v_pu_max",
    "v_pu_min_phase1",
    "v_pu_max_phase1",
    "v_pu_min_phase2",
    "v_pu_max_phase2",
    "v_pu_min_phase3",
    "v_pu_max_phase3",
    "losses_kw",
    "losses_kvar",
    "feeder_head_p_kw",
    "feeder_head_q_kvar",
    "solve_time_s",
]

if not VALIDATION_LOG.exists():
    with open(VALIDATION_LOG, "w", newline="") as f:
        csv.DictWriter(f, fieldnames=VALIDATION_FIELDS).writeheader()


def log_validation_row(timestamp, datetime_str, metrics):
    per_phase = metrics["v_pu_per_phase"]
    all_mins = [p["min"] for p in per_phase.values()]
    all_maxs = [p["max"] for p in per_phase.values()]

    row = {
        "timestamp": timestamp,
        "datetime": datetime_str,
        "converged": metrics["converged"],
        "iterations": metrics["iterations"],
        "v_pu_min": min(all_mins),
        "v_pu_max": max(all_maxs),
        "losses_kw": metrics["losses_kw"],
        "losses_kvar": metrics["losses_kvar"],
        "feeder_head_p_kw": metrics["feeder_head_p_kw"],
        "feeder_head_q_kvar": metrics["feeder_head_q_kvar"],
        "solve_time_s": metrics["solve_time_s"],
    }

    for phase in ("1", "2", "3"):
        bounds = per_phase.get(phase)
        row[f"v_pu_min_phase{phase}"] = bounds["min"] if bounds else ""
        row[f"v_pu_max_phase{phase}"] = bounds["max"] if bounds else ""

    with open(VALIDATION_LOG, "a", newline="") as f:
        csv.DictWriter(f, fieldnames=VALIDATION_FIELDS).writerow(row)

# --------------------------------------------------
# Load representative meters
# --------------------------------------------------

REPRESENTATIVE_METERS = (
    BASE_DIR /
    "simulation" /
    "representative_meters.json"
)

with open(REPRESENTATIVE_METERS, "r") as f:
    representative_meters = json.load(f)

EXPECTED_METERS = len(representative_meters)

print(f"Loaded {EXPECTED_METERS} representative meters")

# --------------------------------------------------
# Load pseudo-measurement series for unmetered nodes (RES.md D10 Phase 1
# item (iv) / RES.md 3.1.4). These are ground-truth Layer-1 drive values
# for the 42 IEEE-123 loads that have no meter, generated by
# simulation/generate_scaled_datasets.py -- NOT published on Kafka, since
# they are not measurements. Held static at nominal was the Phase-0
# defect (RES.md 3.1.4); each is now an explicit time series with a
# recorded sigma_pseudo in data/pseudo_measurement_registry.json.
# --------------------------------------------------

PSEUDO_LOAD_DIR = BASE_DIR / "data" / "pseudo_loads"

pseudo_loads = {}

if PSEUDO_LOAD_DIR.exists():
    for csv_path in sorted(PSEUDO_LOAD_DIR.glob("*.csv")):
        load_name = csv_path.stem
        pseudo_loads[load_name] = pd.read_csv(csv_path)

print(f"Loaded {len(pseudo_loads)} pseudo-load series for unmetered nodes")

# --------------------------------------------------
# Compile IEEE-123 feeder
# --------------------------------------------------
#Without this, your consumer never loads the OpenDSS model.
compile_feeder()

# --------------------------------------------------
# Extract circuit topology once at startup (RES.md D4/D10 Phase 0)
# --------------------------------------------------

N_PHASE_NODES, ALL_NODE_NAMES = get_circuit_topology()

print(f"N_phase_nodes: {N_PHASE_NODES}")

TOPOLOGY_SNAPSHOT = (
    BASE_DIR /
    "artifacts" /
    "circuit_topology.json"
)
TOPOLOGY_SNAPSHOT.parent.mkdir(exist_ok=True)

with open(TOPOLOGY_SNAPSHOT, "w") as f:
    json.dump(
        {
            "n_phase_nodes": N_PHASE_NODES,
            "all_node_names": ALL_NODE_NAMES,
        },
        f,
        indent=2,
    )

# --------------------------------------------------
# Create output CSV
# --------------------------------------------------

if not DIGITAL_TWIN_OUTPUT.exists():

    with open(DIGITAL_TWIN_OUTPUT, "w", newline="") as f:

        writer = csv.writer(f)

        writer.writerow([
            "timestamp",
            "datetime",
            "meter_id",
            "load_name",
            "bus",

            "p_kw",
            "q_kvar",

            "bus_voltage_pu",
            "bus_voltage_v",
            "current_a",
        ])

# --------------------------------------------------
# Kafka Consumer
# --------------------------------------------------

consumer = KafkaConsumer(
    TOPIC,
    bootstrap_servers=BOOTSTRAP_SERVERS,
    value_deserializer=lambda m: json.loads(m.decode("utf-8")),
    auto_offset_reset="earliest",
    group_id="smartgrid",
)

# --------------------------------------------------
# Buffer
# --------------------------------------------------

buffer = defaultdict(dict)

print("Waiting for messages...\n")

# ==================================================
# Main Loop
# ==================================================

for record in consumer:

    message = record.value

    print("Received:")
    print(message)
    print()

    timestamp = message["timestamp"]
    meter_id = message["meter_id"]

    # Store message
    buffer[timestamp][meter_id] = message

    # ---------------------------------------------
    # Wait until every representative meter arrives
    # ---------------------------------------------

    if len(buffer[timestamp]) < EXPECTED_METERS:
        continue

    print(f"\nTimestamp {timestamp} complete")

    messages = buffer[timestamp]

    # ---------------------------------------------
    # Update OpenDSS -- metered loads (from Kafka telemetry)
    # ---------------------------------------------

    for msg in messages.values():

        dss.Loads.Name(msg["load_name"])

        dss.Loads.kW(msg["p_kw"])

        dss.Loads.kvar(msg["q_kvar"])

    # ---------------------------------------------
    # Update OpenDSS -- pseudo loads (unmetered nodes, ground truth only,
    # never published to Kafka; RES.md D10 Phase 1 item (iv))
    # ---------------------------------------------

    for load_name, series in pseudo_loads.items():

        if timestamp >= len(series):
            continue

        row = series.iloc[timestamp]

        dss.Loads.Name(load_name)
        dss.Loads.kW(float(row["p_kw"]))
        dss.Loads.kvar(float(row["q_kvar"]))

    # ---------------------------------------------
    # Solve ONLY ONCE
    # ---------------------------------------------

    solve_start = time.perf_counter()
    dss.Solution.Solve()
    solve_time_s = time.perf_counter() - solve_start

    solution_metrics = get_solution_metrics(solve_time_s)

    sample_datetime = next(iter(messages.values()))["datetime"]
    log_validation_row(timestamp, sample_datetime, solution_metrics)

    #debug
    if not dss.Solution.Converged():

        print(f"Power flow failed at timestamp {timestamp}")

        del buffer[timestamp]

        continue
    # ---------------------------------------------
    # Extract telemetry
    # ---------------------------------------------

    rows = []

    for msg in messages.values():

        telemetry = get_load_telemetry(msg["load_name"])

        row = {
            "timestamp": msg["timestamp"],
            "datetime": msg["datetime"],
            "meter_id": msg["meter_id"],
            "load_name": msg["load_name"],
            "bus": msg["bus"],

            # Input values
            "p_kw": msg["p_kw"],
            "q_kvar": msg["q_kvar"],

            # OpenDSS results
            "bus_voltage_pu": telemetry["voltage_pu"],
            "bus_voltage_v": telemetry["voltage_v"],
            "current_a": telemetry["current_a"],
        }

        rows.append(row)

    print(
        f"Timestamp {timestamp}: "
        f"generated {len(rows)} telemetry rows")

    with open(DIGITAL_TWIN_OUTPUT, "a", newline="") as f:

        writer = csv.DictWriter(
            f,
            fieldnames=[
                "timestamp",
                "datetime",
                "meter_id",
                "load_name",
                "bus",

                "p_kw",
                "q_kvar",

                "bus_voltage_pu",
                "bus_voltage_v",
                "current_a",
            ]
        )

        writer.writerows(rows)
        f.flush()
print(f"Saved {len(rows)} rows")
   
    # ---------------------------------------------
    # Clear timestamp buffer
    # ---------------------------------------------
del buffer[timestamp]